baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Mo Really Sample Hugo Website'
theme = 'ananke'

DefaultContentLanguage = "en"
SectionPagesMenu = "main"

[params]
  author = "Mo Really"
  description  = "Sample Description of what ever"

